### ISSUE TITLE
SEGV in goose_publisher binary

### ISSUE THREAD

**Issue by c0d3xpl0it** [mz-automation/libiec61850#169]
Hello we found SEGV in goose_publisher binary using ASAN.

Machine Setup  
```
OS : Ubuntu 16.04.3 LTS
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
```
Below are commands used.
```
git clone https://github.com/mz-automation/libiec61850
cd libiec61850/
mkdir build ; cd build
cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=leak -g -ggdb -fno-omit-frame-pointer -static-libstdc++ -static-libasan" -DCMAKE_C_FLAGS="-fsanitize=address -fsanitize=leak -g -ggdb -fno-omit-frame-pointer -static-libstdc++ -static-libasan" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address -fsanitize=leak -ggdb -fno-omit-frame-pointer -static-libstdc++ -static-libasan" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address -fsanitize=leak -ggdb -fno-omit-frame-pointer -static-libstdc++ -static-libasan"
AFL_USE_ASAN=1 make
cd examples/goose_publisher
./goose_publisher_example eth0
Using interface eth0
Error creating raw socket!
ASAN:SIGSEGV
=================================================================
==14989==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004e3b16 bp 0x7ffd2b66c7c0 sp 0x7ffd2b66c7a0 T0)
    #0 0x4e3b15 in Ethernet_sendPacket /home/fuzz/temp/libiec61850/hal/ethernet/linux/ethernet_linux.c:230
    #1 0x4d8744 in GoosePublisher_publish /home/fuzz/temp/libiec61850/src/goose/goose_publisher.c:381
    #2 0x4c5ecf in main /home/fuzz/temp/libiec61850/examples/goose_publisher/goose_publisher_example.c:63
    #3 0x7f52c73f682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x41ac08 in _start (/home/fuzz/temp/libiec61850/build/examples/goose_publisher/goose_publisher_example+0x41ac08)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fuzz/temp/libiec61850/hal/ethernet/linux/ethernet_linux.c:230 Ethernet_sendPacket
==14989==ABORTING
```

**Comment by mzillgith** [comment]
Hello. The example has no error handling. You have to provide an exisitng ethernet interface and the example has to be started with permission to open raw socket. A real application would have to check these conditions.
