### ISSUE TITLE
AccessViolationException when constructing IedServer without Logical Devices

### ISSUE THREAD

**Issue by andy1547** [mz-automation/libiec61850#218]
Exception:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at IEC61850.Server.IedServer.IedServer_createWithConfig(IntPtr modelRef, IntPtr tlsConfiguration, IntPtr serverConfiguratio)
   at IEC61850.Server.IedServer..ctor(IedModel iedModel, IedServerConfig config) in C:\Path-To_Projects\libiec61850\dotnet\IEC61850forCSharp\IEC61850ServerAPI.cs:line 1307
   at server1.MainClass.Main(String[] args) in C:\Path-To_Projects\libiec61850\dotnet\server1\Program.cs:line 21
````
Sample .NET code to reproduce issue:
````
IedModel iedModel = new IedModel("myIed");
var iedServer = new IedServer(iedModel);
````
Expected behaviour- the IED Server is started but has no Logical Devices.

**Comment by mzillgith** [comment]
Do you have a specific application for this? The only use case I can imagine is when you want to use only file service.

**Comment by andy1547** [comment]
Our software periodically refreshes the configuration to pick up changes made by users, when this happens it's possible the user has only setup an IED and not yet added their first Logical Device.
Thanks for the fix.
