### ISSUE TITLE
connectionHandlingThread segmentation fault

### ISSUE THREAD

**Issue by arturioxas** [mz-automation/libiec61850#235]
Hello,

I'm building a client app that relies on encrypted transmission. The stack is working well in general, however, as server closes the connection remotely, segmentation fault is received. Got the backtrace which makes me assume that problem probably lies in TLSSocket_close() function:

```double free or corruption (out)
Thread 2 "iec61850-client" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5a9a700 (LWP 24143)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6081801 in __GI_abort () at abort.c:79
#2  0x00007ffff60ca897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff61f7b9a "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff60d190a in malloc_printerr (str=str@entry=0x7ffff61f9870 "double free or corruption (out)")
    at malloc.c:5350
#4  0x00007ffff60d8e75 in _int_free (have_lock=0, p=0x7ffff0006250, av=0x7ffff642cc40 <main_arena>)
    at malloc.c:4278
#5  __GI___libc_free (mem=0x7ffff0006260) at malloc.c:3124
#6  0x00007ffff7b6d435 in Memory_free (memb=0x7ffff0006260)
    at /home/arturas/Downloads/libiec61850/hal/memory/lib_memory.c:82
#7  0x00007ffff7b6dfe5 in TLSSocket_close (self=0x7ffff0006260)
    at /home/arturas/Downloads/libiec61850/hal/tls/mbedtls/tls_mbedtls.c:501
#8  0x00007ffff7b162e8 in releaseSocket (self=0x5555559001f0)
    at /home/arturas/Downloads/libiec61850/src/mms/iso_client/iso_client_connection.c:287
#9  0x00007ffff7b16980 in IsoClientConnection_handleConnection (self=0x5555559001f0)
    at /home/arturas/Downloads/libiec61850/src/mms/iso_client/iso_client_connection.c:600
#10 0x00007ffff7af9018 in MmsConnection_tick (self=0x5555558fdb40)
    at /home/arturas/Downloads/libiec61850/src/mms/iso_mms/client/mms_client_connection.c:1759
#11 0x00007ffff7af86d5 in connectionHandlingThread (parameter=0x5555558fdb40)
    at /home/arturas/Downloads/libiec61850/src/mms/iso_mms/client/mms_client_connection.c:1403
#12 0x00007ffff78a96db in start_thread (arg=0x7ffff5a9a700) at pthread_create.c:463
#13 0x00007ffff616288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95```

**Comment by arturioxas** [comment]
Solved the problem myself. Turns out that every time connection is made or reestablished one should fully create connection from scratch and then connect to it
