### ISSUE TITLE
Issue while reading multiple data objects ReadMultipleVariables function in C#

### ISSUE THREAD

**Issue by Saleem344** [mz-automation/libiec61850#263]
I'm getting error in ReadMultipleVariables function 
System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToInt16(String value, Int32 fromBase)

this issue in only when the object group has four sub groups
like this 
![Screenshot_3](https://user-images.githubusercontent.com/61460632/93994672-c5ec7900-fdad-11ea-9729-9c8a7e82ea3e.png)
or 
![Screenshot_5](https://user-images.githubusercontent.com/61460632/94004473-621c7d00-fdba-11ea-8c00-ed46da691fc2.png)
or group is having subgroups 
![Screenshot_6](https://user-images.githubusercontent.com/61460632/94004489-69dc2180-fdba-11ea-8870-f8d5e2cfa864.png)
under subgroups data is available ReadMultipleVariables  is not working
![Screenshot_7](https://user-images.githubusercontent.com/61460632/94004615-9859fc80-fdba-11ea-8968-2bb6f9092c0a.png)

but when the object group is having only 3 sub groups it is working fine 
![Screenshot_4](https://user-images.githubusercontent.com/61460632/93994432-81f97400-fdad-11ea-8d41-b11495322a31.png)

can you modify the library when there is 4 sub groups also it has read the group.

i'm sharing the link for .icd file for your reference 

https://drive.google.com/file/d/1dvigPTKuMsVO4q2LaCBZSkFVYrFM7LFd/view?usp=sharing

Thank you for support 
please let me know the result, I will be waiting for your reply.

**Comment by Saleem344** [comment]
> I'm getting error in ReadMultipleVariables function
> System.FormatException: Could not find any recognizable digits.
> at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
> at System.Convert.ToInt16(String value, Int32 fromBase)
> 
> this issue in only when the object group has four sub groups
> like this
> ![Screenshot_3](https://user-images.githubusercontent.com/61460632/93994672-c5ec7900-fdad-11ea-9729-9c8a7e82ea3e.png)
> or
> ![Screenshot_5](https://user-images.githubusercontent.com/61460632/94004473-621c7d00-fdba-11ea-8c00-ed46da691fc2.png)
> or group is having subgroups
> ![Screenshot_6](https://user-images.githubusercontent.com/61460632/94004489-69dc2180-fdba-11ea-8870-f8d5e2cfa864.png)
> under subgroups data is available ReadMultipleVariables is not working
> ![Screenshot_7](https://user-images.githubusercontent.com/61460632/94004615-9859fc80-fdba-11ea-8968-2bb6f9092c0a.png)
> 
> but when the object group is having only 3 sub groups it is working fine
> ![Screenshot_4](https://user-images.githubusercontent.com/61460632/93994432-81f97400-fdad-11ea-8d41-b11495322a31.png)
> 
> can you modify the library when there is 4 sub groups also it has read the group.
> 
> i'm sharing the link for .icd file for your reference
> 
> https://drive.google.com/file/d/1dvigPTKuMsVO4q2LaCBZSkFVYrFM7LFd/view?usp=sharing
> 
> Thank you for support
> please let me know the result, I will be waiting for your reply.

Hi, I have solved this issue  and developed  my own IEC61850 client  api in .netcore (https://github.com/Saleem344/ASP.Net-Core-IEC61850-API ) have look
