### ISSUE TITLE
i got a bug in /src/mms/iso_cotp/cotp.c  the libiec version is 1.4.2.1

### ISSUE THREAD

**Issue by tingkman** [mz-automation/libiec61850#455]
i used version libiec61850-1.4.2.1,  the app is got a error and Generate a core
i used gdb app core,and get error in cotp.c 
`warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/mnt/tn/tn_kernal_335x_common'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb49aa452 in CotpConnection_sendDataMessage (self=0xb2624488, payload=0xaccfe9fc) at src/mms/iso_cotp/cotp.c:257
257	src/mms/iso_cotp/cotp.c: No such file or directory.
[Current thread is 1 (LWP 24877)]
(gdb) bt
**#0  0xb49aa452 in CotpConnection_sendDataMessage (self=0xb2624488, payload=0xaccfe9fc) at src/mms/iso_cotp/cotp.c:257**
#1  0xb49976d8 in IsoConnection_sendMessage (self=0xb26907d8, message=0xaeb64d48) at src/mms/iso_server/iso_connection.c:656
#2  0xb498396e in MmsServerConnection_sendMessage (self=0xb2648418, message=0xaeb64d48) at src/mms/iso_mms/server/mms_server_connection.c:781
#3  0xb49a1204 in sendNextReportEntrySegment (self=0xaf3cbe58) at src/iec61850/server/mms_mapping/reporting.c:2751
#4  0xb49a1350 in sendNextReportEntry (self=0xaf3cbe58) at src/iec61850/server/mms_mapping/reporting.c:2811
#5  0xb49a15aa in Reporting_sendReports (self=0xb25000d8, connection=0xb2648418) at src/iec61850/server/mms_mapping/reporting.c:2927
#6  0xb499c132 in mmsConnectionHandler (parameter=0xb25000d8, connection=0xb2648418, event=MMS_SERVER_CONNECTION_TICK) at src/iec61850/server/mms_mapping/mms_mapping.c:2399
#7  0xb498065e in MmsServer_callConnectionHandler (self=0xaeb63aa0, connection=0xb2648418) at src/mms/iso_mms/server/mms_server.c:517
#8  0xb4983844 in connectionTickHandler (parameter=0xb2648418) at src/mms/iso_mms/server/mms_server_connection.c:712
#9  0xb4996de8 in IsoConnection_handleTcpConnection (self=0xb26907d8, isSingleThread=false) at src/mms/iso_server/iso_connection.c:169
#10 0xb4997386 in handleTcpConnection (parameter=0xb26907d8) at src/mms/iso_server/iso_connection.c:471
#11 0xb6f61f5c in ?? () from /lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
`
![image](https://github.com/mz-automation/libiec61850/assets/34257048/c90ffb57-2bab-46f2-9ecc-4b03ca6cc544)
i look 257 row  for bellow 
**buffer[bufPos++] = currentChain->buffer[currentChainIndex];**

i becompare 1.4.2.1 and 1.5.0 fond a different  in sendbuffer

![image](https://github.com/mz-automation/libiec61850/assets/34257048/7c3c5c14-be5a-42c7-9baa-c49b6f3c77dd)

can it Deal with my  issue ？

**Comment by tingkman** [comment]
![image](https://github.com/mz-automation/libiec61850/assets/34257048/983434bb-41e1-46c4-8a9c-ec39a39375ee)

**Comment by tingkman** [comment]
@stv0g @DavidKorczynski  can you see my assiue

**Comment by stv0g** [comment]
Hi @tingkman, why did you referenced me in this issue? I am not actively involved in the development of this code..

**Comment by tingkman** [comment]
> Hi @tingkman, why did you referenced me in this issue? I am not actively involved in the development of this code..


I thought you were familiar with that，sorry

**Comment by mzillgith** [comment]
The version you mentioned is very old. Why don't you try a newer version?
