### ISSUE TITLE
Error importing pyiec61850 in v1.6

### ISSUE THREAD

**Issue by caiods-sh** [mz-automation/libiec61850#523]
I followed the instructions at `/pyiec61850/README.md`. It builds and installs the library, but when i run the tests i get this error:
```bash
pyiec61850$ python3.10 test_pyiec61850.py 
Traceback (most recent call last):
  File "/home/softwares/libiec61850/pyiec61850/test_pyiec61850.py", line 9, in <module>
    import pyiec61850 as iec61850
  File "/usr/local/lib/python3.10/dist-packages/pyiec61850.py", line 15, in <module>
    import _pyiec61850
ImportError: /usr/local/lib/python3.10/dist-packages/_pyiec61850.so: undefined symbol: GoosePublisher_createRemote
```

**Comment by rahatN-tech** [comment]
similar problem is happening with me as well..i am getting the following error
`D:\python\comm\build\pyiec61850\_iec61850.vcxproj]
iec61850PYTHON_wrap.obj : error LNK2019: unresolved external symbol MmsGooseControlBlock_getFixedOffs referenced in function _wrap_MmsGooseControlBlock_getFixedO 
ffs [D:\python\comm\build\pyiec61850\_iec61850.vcxproj]
iec61850PYTHON_wrap.obj : error LNK2019: unresolved external symbol MmsGooseControlBlock_getNdsCom referenced in function _wrap_MmsGooseControlBlock_getNdsCom [D 
:\python\comm\build\pyiec61850\_iec61850.vcxproj]
D:\python\comm\build\pyiec61850\Release\_iec61850.pyd : fatal error LNK1120: 9 unresolved externals [D:\python\comm\build\pyiec61850\_iec61850.vcxproj]`

even though in build..i dont want to use GOOSE..So in CMakeLists.txt file i am setting it as `cmake -DBUILD_PYTHON_BINDINGS=ON -DCONFIG_INCLUDE_GOOSE_SUPPORT=OFF`..still i am unable to link the bindings with my project...also removed goose related files from swig interfacing files with .i extension....please resolve the issue ..badly stuck it it

**Comment by edugdl** [comment]
Same error as @caiobacode

**Comment by 11chri** [comment]
I'm running in the same error. Could you meanwhile fine a solution for a workaround?

**Comment by 11chri** [comment]
I could get the library compiled now: I compiled it in Ubuntu Docker container with using VS Code Dev Containers - see my setup for that:

[DevContainer_Setup.zip](https://github.com/user-attachments/files/18558679/DevContainer_Setup.zip)

**Comment by Dosclic98** [comment]
> I could get the library compiled now: I compiled it in Ubuntu Docker container with using VS Code Dev Containers - see my setup for that:
> 
> [DevContainer_Setup.zip](https://github.com/user-attachments/files/18558679/DevContainer_Setup.zip)

Thanks, this worked for me!

**Comment by rvp2006** [comment]
> Same error as [@caiobacode](https://github.com/caiobacode)

Do you have a workaround for this one
