### ISSUE TITLE
Problem when generating model configuration file

### ISSUE THREAD

**Issue by davideandreuzza** [mz-automation/libiec61850#54]
When I run genconfig.jar, I get the following exception:

```
parse IED section ...
Exception in thread "main" java.lang.NumberFormatException: For input string: "0,01"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at java.lang.Float.<init>(Unknown Source)
	at com.libiec61850.scl.model.DataModelValue.<init>(DataModelValue.java:113)
	at com.libiec61850.scl.model.LogicalNode.parseDataAttributeNodes(LogicalNode.java:191)
	at com.libiec61850.scl.model.LogicalNode.parseSubDataInstances(LogicalNode.java:220)
	at com.libiec61850.scl.model.LogicalNode.<init>(LogicalNode.java:169)
	at com.libiec61850.scl.model.LogicalDevice.parseLogicalNodes(LogicalDevice.java:65)
	at com.libiec61850.scl.model.LogicalDevice.<init>(LogicalDevice.java:49)
	at com.libiec61850.scl.model.Server.<init>(Server.java:52)
	at com.libiec61850.scl.model.AccessPoint.<init>(AccessPoint.java:48)
	at com.libiec61850.scl.model.IED.<init>(IED.java:50)
	at com.libiec61850.scl.SclParser.parseIedSections(SclParser.java:240)
	at com.libiec61850.scl.SclParser.<init>(SclParser.java:89)
	at com.libiec61850.scl.SclParser.<init>(SclParser.java:102)
	at com.libiec61850.tools.DynamicModelGenerator.<init>(DynamicModelGenerator.java:62)
	at com.libiec61850.tools.DynamicModelGenerator.main(DynamicModelGenerator.java:454)

```
The problem is that my CID file contains some Vals of float DAIs that are initialized with the comma as a decimal separator, and the constructor of Java Float objects only accepts the dot as decimal separator.
I looked in the standard, and I only found this section in IEC61850-6 that describes the XML schema for the values:

```
<xs:complexType name="tVal">
   <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
         <xs:attribute name="sGroup" type="xs:unsignedInt" use="optional"/>
      </xs:extension>
   </xs:simpleContent>
</xs:complexType>
```

It is not clear to me whether the comma separator is accepted or not. Is it possible to make the Java program more robust?

**Comment by mzillgith** [comment]
I am not an XML expert but I think the "," as decimal separator is not allowed.
E.g. http://books.xmlschemata.org/relaxng/ch19-77095.html
writes: "The decimal separator is always a point (.), and no thousands separator may be added."
I can replace in the input string the "," by ".". That might work if no "thousands separator" is used.
What tool has created this CID file?

**Comment by davideandreuzza** [comment]
If the data type of tVal had been xsd:float, you'd be right. But, referring to IEC61850-6, the type is and extension of xs:normalizedString, that is...a string (http://books.xmlschemata.org/relaxng/ch19-77263.html). I only found this on the standard.

The CID file seems created by Kalkitech SCL Manager IEC61850 Configuration Tool.

**Comment by mzillgith** [comment]
I had a look in 61850-6. It is a bit confusing. In section 9.5.4.1 it is specified that a "Val" element representing a float has to follow the XML schema xs:double. Therefore the "." would be mandatory as decimal separator. But in the same row it uses "999,99999" as an example ;-) So the standard is not consistent.
I think the best would be to replace "," by "." before parsing.

**Comment by davideandreuzza** [comment]
Thanks
